import os
import sys
# DON'T CHANGE THIS !!!
sys.path.insert(0, os.path.dirname(os.path.dirname(__file__)))

import secrets # For generating a default secret key
from flask import Flask, send_from_directory, render_template # Added render_template
from flask_cors import CORS
from src.models.user import db
from src.routes.user import user_bp
from src.routes.file_processor import file_processor_bp
from src.routes.ships import ships_bp

# Define base directory for robust path construction
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

STATIC_FOLDER_PATH = os.path.join(BASE_DIR, 'static')
TEMPLATE_FOLDER_PATH = os.path.join(BASE_DIR, 'templates')

app = Flask(__name__, template_folder=TEMPLATE_FOLDER_PATH, static_folder=STATIC_FOLDER_PATH)

# Load secret key from environment variable or use a default (less secure, for development only)
SECRET_KEY_VALUE = os.environ.get('MARITIME_SECRET_KEY')
if not SECRET_KEY_VALUE:
    print("WARNING: MARITIME_SECRET_KEY environment variable not set. Using default development key.", file=sys.stderr)
    print("WARNING: For production, set a strong, unique MARITIME_SECRET_KEY environment variable.", file=sys.stderr)
    SECRET_KEY_VALUE = secrets.token_hex(32) # Generate a random key for development if not set

app.config['SECRET_KEY'] = SECRET_KEY_VALUE
app.config['MAX_CONTENT_LENGTH'] = 16 * 1024 * 1024  # 16MB max file size

# Enable CORS for all routes
CORS(app)

app.register_blueprint(user_bp, url_prefix='/api')
app.register_blueprint(file_processor_bp)
app.register_blueprint(ships_bp)

app.config['SQLALCHEMY_DATABASE_URI'] = f"sqlite:///{os.path.join(BASE_DIR, 'database', 'app.db')}"
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
db.init_app(app)

with app.app_context():
    db.create_all()

@app.route('/')
def index():
    return render_template('index.html')

@app.route('/master')
def master_dashboard():
    return render_template('master-dashboard.html')

@app.route('/calendar')
def calendar_view():
    return render_template('calendar.html')

@app.route('/analytics')
def analytics_view():
    return render_template('analytics.html')

# The old serve function is removed. Flask will handle static files from the 'static_folder'
# automatically via the /static/ URL prefix generated by url_for('static', filename='...').
# If there are any files that were expected to be served from the root path (e.g. /favicon.ico)
# and were previously in the static folder, they would need specific routes or to be handled
# by a webserver like Nginx in production. Given the current HTMLs rely on CDNs or inline assets,
# this simplification should be okay for now.

if __name__ == '__main__':
    port = int(os.environ.get('PORT', 5000))
    app.run(host='0.0.0.0', port=port, debug=False)
